-- MTF Questions: column_a, column_b, correct_mapping UPDATE statements
-- Generated for 44 accountancy MTF questions
-- Date: 2026-04-03

-- cuet-acc-npo-bs-20: Match the NPO items with their Balance Sheet presentation:  
UPDATE med_questions SET payload = payload || '{"column_a": [{"id": "i", "text": "Outstanding Subscriptions"}, {"id": "ii", "text": "Advance Subscriptions"}, {"id": "iii", "text": "Capital Fund"}, {"id": "iv", "text": "Building Fund Donations"}], "column_b": [{"id": "P", "text": "Liability — specific fund"}, {"id": "Q", "text": "Asset — current"}, {"id": "R", "text": "Liability — members'' fund"}, {"id": "S", "text": "Liability — income received in advance"}], "correct_mapping": {"i": "Q", "ii": "S", "iii": "R", "iv": "P"}}'::jsonb WHERE id = '33a81d09-9132-4df2-9418-a45821883f6f';

-- cuet-acc-npo-ie-20: Match the following items with their treatment:  Column I: (
UPDATE med_questions SET payload = payload || '{"column_a": [{"id": "i", "text": "Annual subscription"}, {"id": "ii", "text": "Life Membership Fees"}, {"id": "iii", "text": "Sale of old sports material"}, {"id": "iv", "text": "Depreciation on furniture"}], "column_b": [{"id": "P", "text": "Revenue income in I&E Account"}, {"id": "Q", "text": "Non-cash expense in I&E Account"}, {"id": "R", "text": "Capital receipt — Capital Fund on B/S"}, {"id": "S", "text": "Revenue income in I&E Account"}], "correct_mapping": {"i": "P", "ii": "R", "iii": "S", "iv": "Q"}}'::jsonb WHERE id = 'e6bebd20-e206-46b8-858c-564d9b49e46e';

-- cuet-acc-npo-rp-20: Match the following NPO terms:  Column I: (i) Receipts & Pay
UPDATE med_questions SET payload = payload || '{"column_a": [{"id": "i", "text": "Receipts & Payments Account"}, {"id": "ii", "text": "Income & Expenditure Account"}, {"id": "iii", "text": "Capital Fund"}, {"id": "iv", "text": "Life Membership Fees"}], "column_b": [{"id": "P", "text": "Equivalent to Profit & Loss Account"}, {"id": "Q", "text": "Added to Capital Fund directly"}, {"id": "R", "text": "Excess of assets over liabilities"}, {"id": "S", "text": "Summary of cash transactions"}], "correct_mapping": {"i": "S", "ii": "P", "iii": "R", "iv": "Q"}}'::jsonb WHERE id = '920f584b-81c7-411b-8957-9a96edb28fd0';

-- cuet-acc-partner-fundamentals-17: Match the following items with their correct accounting trea
UPDATE med_questions SET payload = payload || '{"column_a": [{"id": "i", "text": "Interest on Capital"}, {"id": "ii", "text": "Interest on Partner''s Loan"}, {"id": "iii", "text": "Interest on Drawings"}, {"id": "iv", "text": "Partner''s Salary"}], "column_b": [{"id": "P", "text": "Charge against profit — debited to P&L Account"}, {"id": "Q", "text": "Appropriation — debited to P&L Appropriation Account"}, {"id": "R", "text": "Credited to P&L Appropriation Account"}, {"id": "S", "text": "Appropriation — debited to P&L Appropriation Account"}], "correct_mapping": {"i": "Q", "ii": "P", "iii": "R", "iv": "S"}}'::jsonb WHERE id = '226f314c-c671-4ca2-935a-00bf1345e751';

-- cuet-acc-partner-advanced-17: Match the following partnership terms with their correct des
UPDATE med_questions SET payload = payload || '{"column_a": [{"id": "i", "text": "Mutual Agency"}, {"id": "ii", "text": "Profit & Loss Appropriation Account"}, {"id": "iii", "text": "Fixed Capital Method"}, {"id": "iv", "text": "Interest on Partner''s Loan"}], "column_b": [{"id": "P", "text": "Each partner is an agent of the firm and principal of other partners"}, {"id": "Q", "text": "Two accounts maintained — Capital Account and Current Account"}, {"id": "R", "text": "A charge against profit, debited to P&L Account"}, {"id": "S", "text": "Shows the distribution of net profit among partners"}], "correct_mapping": {"i": "P", "ii": "S", "iii": "Q", "iv": "R"}}'::jsonb WHERE id = '5d3910ec-a966-4281-a37f-9648d731aad2';

-- cuet-acc-partner-guarantee-17: Match the following past adjustment scenarios with the corre
UPDATE med_questions SET payload = payload || '{"column_a": [{"id": "i", "text": "Interest on capital omitted"}, {"id": "ii", "text": "Partner''s salary over-provided"}, {"id": "iii", "text": "Interest on drawings not charged"}, {"id": "iv", "text": "Profits shared in wrong ratio"}], "column_b": [{"id": "P", "text": "Credit the partner who received less profit and debit the one who received more"}, {"id": "Q", "text": "Debit the partner who received excess salary and credit the others"}, {"id": "R", "text": "Credit the partner with higher capital and debit the partner with lower capital (net effect)"}, {"id": "S", "text": "Debit the partner with higher drawings and credit the others (net effect)"}], "correct_mapping": {"i": "R", "ii": "Q", "iii": "S", "iv": "P"}}'::jsonb WHERE id = 'a2bb1434-44da-4a16-b106-7fab1c1775c1';

-- cuet-acc-retire-goodwill-20: Match the goodwill treatment method with its journal entry o
UPDATE med_questions SET payload = payload || '{"column_a": [{"id": "i", "text": "Goodwill adjusted through capitals only"}, {"id": "ii", "text": "Goodwill raised and written off"}, {"id": "iii", "text": "Goodwill raised and retained in books"}, {"id": "iv", "text": "Retiring partner forgoes goodwill"}], "column_b": [{"id": "P", "text": "Goodwill A/c Dr. → To All Partners'' Capital A/c (old ratio); then Remaining Partners'' Capital A/c Dr. (new ratio) → To Goodwill A/c"}, {"id": "Q", "text": "Gaining Partners'' Capital A/c Dr. (gaining ratio) → To C''s Capital A/c"}, {"id": "R", "text": "Goodwill A/c Dr. → To All Partners'' Capital A/c (old ratio)"}, {"id": "S", "text": "No entry for goodwill"}], "correct_mapping": {"i": "Q", "ii": "P", "iii": "R", "iv": "S"}}'::jsonb WHERE id = 'f61cc601-81f8-492c-86e5-8c20ef99de64';

-- cuet-acc-retire-gainingratio-20: Match the following situations with the correct gaining rati
UPDATE med_questions SET payload = payload || '{"column_a": [{"id": "i", "text": "C''s share taken in old ratio of A & B"}, {"id": "ii", "text": "C''s share taken equally by A & B"}, {"id": "iii", "text": "A takes entire share of C"}, {"id": "iv", "text": "B takes entire share of C"}], "column_b": [{"id": "P", "text": "1 : 1"}, {"id": "Q", "text": "2 : 1"}, {"id": "R", "text": "Only A gains"}, {"id": "S", "text": "Only B gains"}], "correct_mapping": {"i": "Q", "ii": "P", "iii": "R", "iv": "S"}}'::jsonb WHERE id = '10e3789b-94e7-4c00-a721-e6ec7a4aa40c';

-- cuet-acc-psr-ratios-17: Match the following items with the ratio in which they are d
UPDATE med_questions SET payload = payload || '{"column_a": [{"id": "i", "text": "General Reserve"}, {"id": "ii", "text": "Revaluation Profit/Loss"}, {"id": "iii", "text": "Goodwill compensation between partners"}, {"id": "iv", "text": "Part II of Memorandum Revaluation Account"}], "column_b": [{"id": "P", "text": "Old Profit-Sharing Ratio"}, {"id": "Q", "text": "Sacrificing/Gaining Ratio"}, {"id": "R", "text": "New Profit-Sharing Ratio"}, {"id": "S", "text": "Old Profit-Sharing Ratio"}], "correct_mapping": {"i": "P", "ii": "S", "iii": "Q", "iv": "R"}}'::jsonb WHERE id = '3bc845f0-bc90-4a66-8a82-650042ed29ef';

-- cuet-acc-admission-goodwill-17: Match the goodwill scenario on admission with the correct ac
UPDATE med_questions SET payload = payload || '{"column_a": [{"id": "i", "text": "New partner brings full goodwill in cash; goodwill not to appear in books"}, {"id": "ii", "text": "New partner cannot bring goodwill in cash"}, {"id": "iii", "text": "Goodwill is to be raised and retained in books"}, {"id": "iv", "text": "Goodwill already exists in books at old value"}], "column_b": [{"id": "P", "text": "Raise goodwill in old ratio and write off in new ratio"}, {"id": "Q", "text": "Dr. Cash, Cr. Old Partners'' Capitals (sacrificing ratio)"}, {"id": "R", "text": "Write off old goodwill in old ratio first"}, {"id": "S", "text": "Dr. Goodwill A/c, Cr. Old Partners'' Capitals (old ratio)"}], "correct_mapping": {"i": "Q", "ii": "P", "iii": "S", "iv": "R"}}'::jsonb WHERE id = '6a113162-d9ea-4860-a9ce-3c3a46029aea';

-- cuet-acc-psr-advanced-17: Match the following Balance Sheet items with their treatment
UPDATE med_questions SET payload = payload || '{"column_a": [{"id": "i", "text": "General Reserve"}, {"id": "ii", "text": "P&L Account (Debit balance)"}, {"id": "iii", "text": "Workmen Compensation Reserve (no claim exists)"}, {"id": "iv", "text": "Advertisement Suspense Account"}], "column_b": [{"id": "P", "text": "Distributed (debited) to partners in old ratio as it is a loss"}, {"id": "Q", "text": "Distributed (credited) to partners in old ratio as it is accumulated profit"}, {"id": "R", "text": "Distributed (credited) to partners in old ratio — full amount is free reserve"}, {"id": "S", "text": "Distributed (debited) to partners in old ratio as it is a deferred expense"}], "correct_mapping": {"i": "Q", "ii": "P", "iii": "R", "iv": "S"}}'::jsonb WHERE id = 'ce3e9d9f-4296-4cb2-8b6d-38d34878969c';

-- cuet-acc-admission-goodwill-ext-15: Match the goodwill method on admission with the correct acco
UPDATE med_questions SET payload = payload || '{"column_a": [{"id": "i", "text": "Premium method — cash retained"}, {"id": "ii", "text": "Premium method — cash withdrawn"}, {"id": "iii", "text": "Goodwill raised and retained"}, {"id": "iv", "text": "Goodwill raised and written off"}], "column_b": [{"id": "A", "text": "Goodwill A/c debited in old ratio, then immediately written off in new ratio; no goodwill appears in Balance Sheet"}, {"id": "B", "text": "Cash/Bank debited; old partners'' capitals credited in sacrificing ratio; premium stays in business"}, {"id": "C", "text": "Goodwill A/c appears as an asset in the new Balance Sheet; old partners'' capitals credited in old ratio"}, {"id": "D", "text": "Cash/Bank debited; old partners'' capitals credited in sacrificing ratio; old partners withdraw the premium"}], "correct_mapping": {"i": "B", "ii": "D", "iii": "C", "iv": "A"}}'::jsonb WHERE id = 'b51226c4-9969-4285-87cd-eb3c83a6a69e';

-- cuet-acc-admission-adjustments-ext-17: Match the Balance Sheet item with its treatment on admission
UPDATE med_questions SET payload = payload || '{"column_a": [{"id": "i", "text": "General Reserve"}, {"id": "ii", "text": "P&L Account (Debit balance)"}, {"id": "iii", "text": "Advertisement Suspense Account"}, {"id": "iv", "text": "Workmen Compensation Reserve (no claim exists)"}], "column_b": [{"id": "A", "text": "Written off by debiting old partners'' capitals in old ratio"}, {"id": "B", "text": "Credited to old partners'' capital accounts in old ratio as it represents accumulated profit"}, {"id": "C", "text": "Debited to old partners'' capitals in old ratio as it represents deferred revenue expenditure"}, {"id": "D", "text": "Entire amount distributed to old partners in old ratio as no liability exists"}], "correct_mapping": {"i": "B", "ii": "A", "iii": "C", "iv": "D"}}'::jsonb WHERE id = '3e04ecae-799d-4ea5-87ae-a2b4c36c8bc3';

-- cuet-acc-retire-newratio-20: Match the following scenarios (A, B, C share profits in 5:3:
UPDATE med_questions SET payload = payload || '{"column_a": [{"id": "i", "text": "B''s share taken in old ratio of A and C"}, {"id": "ii", "text": "B''s share taken equally by A and C"}, {"id": "iii", "text": "A takes entire share of B"}, {"id": "iv", "text": "C takes entire share of B"}], "column_b": [{"id": "P", "text": "7 : 3"}, {"id": "Q", "text": "5 : 2"}, {"id": "R", "text": "13 : 7"}, {"id": "S", "text": "1 : 1"}], "correct_mapping": {"i": "Q", "ii": "R", "iii": "P", "iv": "S"}}'::jsonb WHERE id = '065f7919-a07f-4702-95fd-b41d92ba3216';

-- cuet-acc-retire-reval-20: Match the following adjustments on retirement with the corre
UPDATE med_questions SET payload = payload || '{"column_a": [{"id": "i", "text": "Revaluation profit/loss"}, {"id": "ii", "text": "General Reserve / P&L balance"}, {"id": "iii", "text": "Goodwill to retiring partner (through capitals)"}, {"id": "iv", "text": "Write-off of raised goodwill"}], "column_b": [{"id": "P", "text": "Gaining ratio"}, {"id": "Q", "text": "Old ratio (all partners)"}, {"id": "R", "text": "New ratio (remaining partners)"}, {"id": "S", "text": "Old ratio (all partners)"}], "correct_mapping": {"i": "Q", "ii": "S", "iii": "P", "iv": "R"}}'::jsonb WHERE id = '6393d74c-512f-47c2-b27d-0125864ef371';

-- cuet-acc-dissol-comp-20: Match the following dissolution scenarios with the correct a
UPDATE med_questions SET payload = payload || '{"column_a": [{"id": "i", "text": "Partner takes over asset at agreed value"}, {"id": "ii", "text": "Firm pays realisation expenses"}, {"id": "iii", "text": "Unrecorded liability paid"}, {"id": "iv", "text": "Partner''s loan repaid"}], "column_b": [{"id": "P", "text": "Realisation A/c Dr., Cash A/c Cr."}, {"id": "Q", "text": "Partner''s Capital A/c Dr., Realisation A/c Cr."}, {"id": "R", "text": "Partner''s Loan A/c Dr., Cash A/c Cr."}, {"id": "S", "text": "Realisation A/c Dr., Cash A/c Cr."}], "correct_mapping": {"i": "Q", "ii": "P", "iii": "S", "iv": "R"}}'::jsonb WHERE id = '501e673b-47ca-4d85-b919-8a69381074f7';

-- cuet-acc-dissol-realisation-19: Match the following items with their treatment in Realisatio
UPDATE med_questions SET payload = payload || '{"column_a": [{"id": "i", "text": "Assets at book value"}, {"id": "ii", "text": "External liabilities at book value"}, {"id": "iii", "text": "Sale proceeds of assets"}, {"id": "iv", "text": "Cash/Bank balance"}], "column_b": [{"id": "P", "text": "Credited to Realisation A/c"}, {"id": "Q", "text": "Debited to Realisation A/c"}, {"id": "R", "text": "Not transferred to Realisation A/c"}, {"id": "S", "text": "Credited to Realisation A/c"}], "correct_mapping": {"i": "Q", "ii": "P", "iii": "S", "iv": "R"}}'::jsonb WHERE id = 'd2cd087f-fd2c-486f-b244-01b904a0c215';

-- cuet-acc-dissol-types-18: Match the following Sections of the Indian Partnership Act w
UPDATE med_questions SET payload = payload || '{"column_a": [{"id": "i", "text": "Section 40"}, {"id": "ii", "text": "Section 41"}, {"id": "iii", "text": "Section 43"}, {"id": "iv", "text": "Section 44"}], "column_b": [{"id": "P", "text": "Dissolution by notice (partnership-at-will)"}, {"id": "Q", "text": "Dissolution by agreement"}, {"id": "R", "text": "Compulsory dissolution"}, {"id": "S", "text": "Dissolution by court order"}], "correct_mapping": {"i": "Q", "ii": "R", "iii": "P", "iv": "S"}}'::jsonb WHERE id = '4e993d56-a927-486b-ab20-c1fd0e2a2d34';

-- cuet-acc-dissol-unrecorded-19: Match the following items with their treatment on dissolutio
UPDATE med_questions SET payload = payload || '{"column_a": [{"id": "i", "text": "Partner''s loan to firm"}, {"id": "ii", "text": "Unrecorded liability paid"}, {"id": "iii", "text": "Unrecorded asset sold"}, {"id": "iv", "text": "External creditors paid"}], "column_b": [{"id": "P", "text": "Debited to Realisation A/c, credited to Cash A/c"}, {"id": "Q", "text": "Credited to Realisation A/c, debited to Cash A/c"}, {"id": "R", "text": "Paid directly from Cash — not through Realisation"}, {"id": "S", "text": "Debited to Realisation A/c, credited to Cash A/c"}], "correct_mapping": {"i": "R", "ii": "P", "iii": "Q", "iv": "S"}}'::jsonb WHERE id = '23a3ea3e-0918-4ad4-bede-4a9a0b2622f4';

-- cuet-acc-share-issue-18: Match the following share issue terms with their entries:  |
UPDATE med_questions SET payload = payload || '{"column_a": [{"id": "i", "text": "Application received"}, {"id": "ii", "text": "Application money transferred"}, {"id": "iii", "text": "Allotment due"}, {"id": "iv", "text": "Allotment money received"}], "column_b": [{"id": "P", "text": "Share Allotment Dr. → To Share Capital, To Sec. Premium"}, {"id": "Q", "text": "Bank A/c Dr. → To Share Application A/c"}, {"id": "R", "text": "Share Application A/c Dr. → To Share Capital A/c"}, {"id": "S", "text": "Bank A/c Dr. → To Share Allotment A/c"}], "correct_mapping": {"i": "Q", "ii": "R", "iii": "P", "iv": "S"}}'::jsonb WHERE id = '3e2197dc-8b67-4ed8-8f12-051a1af0ea12';

-- cuet-acc-share-forfeit-18: Match the following scenarios with the correct treatment of 
UPDATE med_questions SET payload = payload || '{"column_a": [{"id": "i", "text": "Shares issued at premium, premium received"}, {"id": "ii", "text": "Shares issued at premium, premium NOT received"}, {"id": "iii", "text": "Shares issued at par"}], "column_b": [{"id": "P", "text": "Securities Premium A/c is debited (reversed)"}, {"id": "Q", "text": "Securities Premium A/c is NOT affected"}, {"id": "R", "text": "No Securities Premium involved"}], "correct_mapping": {"i": "Q", "ii": "P", "iii": "R"}}'::jsonb WHERE id = '93a9bea7-3ae3-4ab0-8e12-d0835eae5388';

-- cuet-acc-deb-issue-prem-18: Match the debenture issue scenario with the correct journal 
UPDATE med_questions SET payload = payload || '{"column_a": [{"id": "i", "text": "Issued at par"}, {"id": "ii", "text": "Issued at premium"}, {"id": "iii", "text": "Issued at discount"}, {"id": "iv", "text": "Issued at discount, redeemable at premium"}], "column_b": [{"id": "P", "text": "Bank Dr. + Loss on Issue Dr."}, {"id": "Q", "text": "Bank Dr."}, {"id": "R", "text": "Bank Dr. + Discount Dr."}, {"id": "S", "text": "Bank Dr."}], "correct_mapping": {"i": "Q", "ii": "S", "iii": "R", "iv": "P"}}'::jsonb WHERE id = '5ceba79e-5ddf-453b-bed9-45c18c9efb4d';

-- cuet-acc-deb-types-15: Match the following types of debentures with their features:
UPDATE med_questions SET payload = payload || '{"column_a": [{"id": "i", "text": "Secured debentures"}, {"id": "ii", "text": "Convertible debentures"}, {"id": "iii", "text": "Bearer debentures"}, {"id": "iv", "text": "Unsecured debentures"}], "column_b": [{"id": "P", "text": "Transferable by mere delivery"}, {"id": "Q", "text": "Backed by charge on company''s assets"}, {"id": "R", "text": "No charge on assets"}, {"id": "S", "text": "Can be converted into equity shares"}], "correct_mapping": {"i": "Q", "ii": "S", "iii": "P", "iv": "R"}}'::jsonb WHERE id = '9f37cb7c-b4ac-4488-b8d1-6252fa2d40a6';

-- cuet-acc-deb-redeem-18: Match the redemption scenario with the correct profit/loss t
UPDATE med_questions SET payload = payload || '{"column_a": [{"id": "i", "text": "Open market purchase below face value"}, {"id": "ii", "text": "Open market purchase above face value"}, {"id": "iii", "text": "Redemption at par (face value)"}, {"id": "iv", "text": "Redemption at premium"}], "column_b": [{"id": "P", "text": "Loss debited to P&L"}, {"id": "Q", "text": "Profit credited to Capital Reserve"}, {"id": "R", "text": "No profit or loss"}, {"id": "S", "text": "Premium debited from Premium on Redemption A/c"}], "correct_mapping": {"i": "Q", "ii": "P", "iii": "R", "iv": "S"}}'::jsonb WHERE id = 'c70d7af9-a106-415d-a3d4-c3e1eaa82568';

-- cuet-acc-deb-drr-18: Match the following debenture events with their accounting t
UPDATE med_questions SET payload = payload || '{"column_a": [{"id": "i", "text": "Creation of DRR"}, {"id": "ii", "text": "Redemption at par"}, {"id": "iii", "text": "Transfer of DRR after redemption"}, {"id": "iv", "text": "Interest accrued"}], "column_b": [{"id": "P", "text": "DRR Dr. → To General Reserve"}, {"id": "Q", "text": "Surplus Dr. → To DRR"}, {"id": "R", "text": "Debentures Dr. → To Bank"}, {"id": "S", "text": "Debenture Interest Dr. → To Debenture Holders"}], "correct_mapping": {"i": "Q", "ii": "R", "iii": "P", "iv": "S"}}'::jsonb WHERE id = 'd6b75da9-6f76-417e-a56c-9017fdccb7bd';

-- cuet-acc-fs-bs-15: Match the following items with their classification in the B
UPDATE med_questions SET payload = payload || '{"column_a": [{"id": "i", "text": "Debentures (long-term)"}, {"id": "ii", "text": "Inventories"}, {"id": "iii", "text": "Securities Premium"}, {"id": "iv", "text": "Trade Receivables"}], "column_b": [{"id": "P", "text": "Current Assets"}, {"id": "Q", "text": "Shareholders'' Funds"}, {"id": "R", "text": "Non-Current Liabilities"}, {"id": "S", "text": "Current Assets"}], "correct_mapping": {"i": "R", "ii": "P", "iii": "Q", "iv": "S"}}'::jsonb WHERE id = '12d5d7d9-c059-45b0-a534-6cd728110258';

-- cuet-acc-fs-pl-14: Match the items with their classification in the Statement o
UPDATE med_questions SET payload = payload || '{"column_a": [{"id": "i", "text": "Sale of scrap"}, {"id": "ii", "text": "Interest on fixed deposits"}, {"id": "iii", "text": "Salary and wages"}, {"id": "iv", "text": "Interest on debentures"}], "column_b": [{"id": "P", "text": "Revenue from Operations"}, {"id": "Q", "text": "Other Income"}, {"id": "R", "text": "Employee Benefits Expense"}, {"id": "S", "text": "Finance Costs"}], "correct_mapping": {"i": "P", "ii": "Q", "iii": "R", "iv": "S"}}'::jsonb WHERE id = 'c6e936c4-6c53-4269-8c5b-7276d1fdc9dc';

-- cuet-acc-sa-comp-012: Match the analysis tool with its primary purpose:  | Column 
UPDATE med_questions SET payload = payload || '{"column_a": [{"id": "i", "text": "Comparative Statement"}, {"id": "ii", "text": "Common Size Statement"}, {"id": "iii", "text": "Trend Analysis"}, {"id": "iv", "text": "Ratio Analysis"}], "column_b": [{"id": "P", "text": "Studying structural composition within a period"}, {"id": "Q", "text": "Studying changes between two periods"}, {"id": "R", "text": "Studying direction of change over multiple periods"}, {"id": "S", "text": "Studying quantitative relationships between two items"}], "correct_mapping": {"i": "Q", "ii": "P", "iii": "R", "iv": "S"}}'::jsonb WHERE id = '20dc63a3-3a19-4d6e-8594-84163d8d9ef4';

-- cuet-acc-sa-comp-stmt-20: Match the tools with their characteristics:  Column I: (i) C
UPDATE med_questions SET payload = payload || '{"column_a": [{"id": "i", "text": "Comparative Statements"}, {"id": "ii", "text": "Common Size Statements"}, {"id": "iii", "text": "Trend Analysis"}, {"id": "iv", "text": "Ratio Analysis"}], "column_b": [{"id": "P", "text": "Expresses each item as percentage of a base item"}, {"id": "Q", "text": "Shows changes over two or more periods"}, {"id": "R", "text": "Establishes quantitative relationships between two items"}, {"id": "S", "text": "Studies data over 5+ years using a base year"}], "correct_mapping": {"i": "Q", "ii": "P", "iii": "S", "iv": "R"}}'::jsonb WHERE id = '5cf214ac-927b-4cce-acf1-1a9ad83efca9';

-- cuet-acc-fs-comp-15: Match the following items with their correct Balance Sheet h
UPDATE med_questions SET payload = payload || '{"column_a": [{"id": "i", "text": "Goodwill"}, {"id": "ii", "text": "Trade Receivables"}, {"id": "iii", "text": "9% Debentures (due after 3 years)"}, {"id": "iv", "text": "Securities Premium Reserve"}], "column_b": [{"id": "P", "text": "Non-Current Assets — Intangible Assets"}, {"id": "Q", "text": "Current Assets"}, {"id": "R", "text": "Non-Current Liabilities — Long-term Borrowings"}, {"id": "S", "text": "Shareholders'' Funds — Reserves and Surplus"}], "correct_mapping": {"i": "P", "ii": "Q", "iii": "R", "iv": "S"}}'::jsonb WHERE id = 'c3c31a48-5b03-40de-9c46-a5fbb82d94b1';

-- cuet-acc-sa-cs-20: Match the following:  Column I: (i) Common Size Balance Shee
UPDATE med_questions SET payload = payload || '{"column_a": [{"id": "i", "text": "Common Size Balance Sheet base"}, {"id": "ii", "text": "Common Size P&L base"}, {"id": "iii", "text": "Comparative Statement shows"}, {"id": "iv", "text": "Common Size Statement shows"}], "column_b": [{"id": "P", "text": "Revenue from Operations"}, {"id": "Q", "text": "Total Assets"}, {"id": "R", "text": "Structural composition as percentages"}, {"id": "S", "text": "Absolute and percentage changes over periods"}], "correct_mapping": {"i": "Q", "ii": "P", "iii": "S", "iv": "R"}}'::jsonb WHERE id = 'e1839d08-9c66-4825-919a-d5cc4e80a14c';

-- cuet-acc-sa-trend-015: Match the following trend observations with their likely int
UPDATE med_questions SET payload = payload || '{"column_a": [{"id": "i", "text": "Inventory trend > Sales trend"}, {"id": "ii", "text": "Revenue trend > Expense trend"}, {"id": "iii", "text": "Borrowings trend declining"}, {"id": "iv", "text": "Fixed Assets trend >> Revenue trend"}], "column_b": [{"id": "P", "text": "Improving debt management"}, {"id": "Q", "text": "Possible overstocking"}, {"id": "R", "text": "Increasing profitability"}, {"id": "S", "text": "Underutilisation of assets"}], "correct_mapping": {"i": "Q", "ii": "R", "iii": "P", "iv": "S"}}'::jsonb WHERE id = '107ac885-a489-47f6-b2ad-303a2d26532d';

-- cuet-acc-fs-adj-18: Match the adjustment items with their Balance Sheet classifi
UPDATE med_questions SET payload = payload || '{"column_a": [{"id": "i", "text": "Prepaid rent"}, {"id": "ii", "text": "Outstanding wages"}, {"id": "iii", "text": "Provision for tax"}, {"id": "iv", "text": "Accrued interest receivable"}], "column_b": [{"id": "P", "text": "Short-term Provisions"}, {"id": "Q", "text": "Other Current Liabilities"}, {"id": "R", "text": "Other Current Assets"}, {"id": "S", "text": "Short-term Loans and Advances"}], "correct_mapping": {"i": "S", "ii": "Q", "iii": "P", "iv": "R"}}'::jsonb WHERE id = '3d960fc1-3de4-4560-9392-2b00ee57a004';

-- cuet-acc-comp-tally-20: Match the Tally shortcut keys with their voucher types:  Col
UPDATE med_questions SET payload = payload || '{"column_a": [{"id": "i", "text": "F4"}, {"id": "ii", "text": "F5"}, {"id": "iii", "text": "F7"}, {"id": "iv", "text": "F8"}], "column_b": [{"id": "P", "text": "Payment Voucher"}, {"id": "Q", "text": "Sales Voucher"}, {"id": "R", "text": "Contra Voucher"}, {"id": "S", "text": "Journal Voucher"}], "correct_mapping": {"i": "R", "ii": "P", "iii": "S", "iv": "Q"}}'::jsonb WHERE id = '02a34d8a-efe6-4892-a54f-885bad96c1b1';

-- cuet-acc-comp-mis-20: Match the MIS report types with their descriptions:  Column 
UPDATE med_questions SET payload = payload || '{"column_a": [{"id": "i", "text": "Ageing Analysis"}, {"id": "ii", "text": "Budget vs Actual"}, {"id": "iii", "text": "Exception Report"}, {"id": "iv", "text": "Stock Summary"}], "column_b": [{"id": "P", "text": "Shows current inventory quantities and values"}, {"id": "Q", "text": "Highlights items deviating from normal thresholds"}, {"id": "R", "text": "Compares planned vs actual financial performance"}, {"id": "S", "text": "Classifies receivables/payables by overdue period"}], "correct_mapping": {"i": "S", "ii": "R", "iii": "Q", "iv": "P"}}'::jsonb WHERE id = '325d8631-0688-4996-be00-dd5b729613d4';

-- cuet-acc-comp-ov-20: Match the CAS concepts:  Column I: (i) Contra Voucher (ii) A
UPDATE med_questions SET payload = payload || '{"column_a": [{"id": "i", "text": "Contra Voucher"}, {"id": "ii", "text": "Audit Trail"}, {"id": "iii", "text": "Codification"}, {"id": "iv", "text": "MIS Reports"}], "column_b": [{"id": "P", "text": "Assigning unique codes to accounts"}, {"id": "Q", "text": "Cash-to-Bank or Bank-to-Cash entry"}, {"id": "R", "text": "Reports for management decision-making"}, {"id": "S", "text": "Log of all data modifications"}], "correct_mapping": {"i": "Q", "ii": "S", "iii": "P", "iv": "R"}}'::jsonb WHERE id = 'baa92baf-79ad-409e-97fd-1b115d42b550';

-- cuet-acc-comp-db-20: Match the CAS reports with their purpose:  Column I: (i) Tri
UPDATE med_questions SET payload = payload || '{"column_a": [{"id": "i", "text": "Trial Balance"}, {"id": "ii", "text": "Balance Sheet"}, {"id": "iii", "text": "Outstanding Report"}, {"id": "iv", "text": "Day Book"}], "column_b": [{"id": "P", "text": "Shows all vouchers entered for a period"}, {"id": "Q", "text": "Shows financial position (assets, liabilities, equity)"}, {"id": "R", "text": "Shows all ledger balances (debit and credit)"}, {"id": "S", "text": "Shows receivables and payables with ageing"}], "correct_mapping": {"i": "R", "ii": "Q", "iii": "S", "iv": "P"}}'::jsonb WHERE id = '0e798ccf-c8ac-48fa-942c-58194e6e6d74';

-- cuet-acc-cfs-oper-20: Match the items with their treatment under the Indirect Meth
UPDATE med_questions SET payload = payload || '{"column_a": [{"id": "i", "text": "Depreciation"}, {"id": "ii", "text": "Profit on sale of land"}, {"id": "iii", "text": "Increase in inventories"}, {"id": "iv", "text": "Decrease in trade receivables"}], "column_b": [{"id": "P", "text": "Added back to Net Profit"}, {"id": "Q", "text": "Deducted from Net Profit"}, {"id": "R", "text": "Deducted (reduces cash flow)"}, {"id": "S", "text": "Added (increases cash flow)"}], "correct_mapping": {"i": "P", "ii": "Q", "iii": "R", "iv": "S"}}'::jsonb WHERE id = '20a05a19-2e7e-42bf-8009-b98745e40768';

-- cuet-acc-cfs-inv-fin-16: Match the items with their activity classification:  Column 
UPDATE med_questions SET payload = payload || '{"column_a": [{"id": "i", "text": "Purchase of building"}, {"id": "ii", "text": "Proceeds from issue of debentures"}, {"id": "iii", "text": "Interest received on investments"}, {"id": "iv", "text": "Dividend paid to shareholders"}], "column_b": [{"id": "P", "text": "Investing Activity — Outflow"}, {"id": "Q", "text": "Financing Activity — Inflow"}, {"id": "R", "text": "Investing Activity — Inflow"}, {"id": "S", "text": "Financing Activity — Outflow"}], "correct_mapping": {"i": "P", "ii": "Q", "iii": "R", "iv": "S"}}'::jsonb WHERE id = 'e8cf028b-5ba2-45f5-a3c8-38e052096c66';

-- cuet-acc-cfs-basics-18: Match the cash flow items with their activity classification
UPDATE med_questions SET payload = payload || '{"column_a": [{"id": "i", "text": "Cash received from customers"}, {"id": "ii", "text": "Purchase of plant and machinery"}, {"id": "iii", "text": "Repayment of long-term borrowings"}, {"id": "iv", "text": "Dividend paid to shareholders"}], "column_b": [{"id": "P", "text": "Operating Activity"}, {"id": "Q", "text": "Investing Activity"}, {"id": "R", "text": "Financing Activity"}], "correct_mapping": {"i": "P", "ii": "Q", "iii": "R", "iv": "R"}}'::jsonb WHERE id = 'f1ba95c7-e2ad-4dd6-9aa2-e41aa46dc441';

-- cuet-acc-cfs-comp-16: Match the following with the correct treatment under Indirec
UPDATE med_questions SET payload = payload || '{"column_a": [{"id": "i", "text": "Depreciation"}, {"id": "ii", "text": "Profit on sale of building"}, {"id": "iii", "text": "Increase in prepaid expenses"}, {"id": "iv", "text": "Decrease in outstanding expenses"}], "column_b": [{"id": "P", "text": "Added back to Net Profit"}, {"id": "Q", "text": "Deducted from Net Profit"}, {"id": "R", "text": "Deducted (reduces operating cash)"}, {"id": "S", "text": "Deducted (reduces operating cash)"}], "correct_mapping": {"i": "P", "ii": "Q", "iii": "R", "iv": "S"}}'::jsonb WHERE id = '3527376b-d8bd-4a84-b3b8-ecd7b6acd2de';

-- cuet-acc-ratio-liq-20: Match the following:  Column I: (i) Current Ratio (ii) Quick
UPDATE med_questions SET payload = payload || '{"column_a": [{"id": "i", "text": "Current Ratio"}, {"id": "ii", "text": "Quick Ratio"}, {"id": "iii", "text": "Liquidity Ratios"}, {"id": "iv", "text": "Ratio Analysis"}], "column_b": [{"id": "P", "text": "Excludes inventory from current assets"}, {"id": "Q", "text": "2:1 ideal"}, {"id": "R", "text": "Measures short-term solvency"}, {"id": "S", "text": "Technique of financial statement analysis"}], "correct_mapping": {"i": "Q", "ii": "P", "iii": "R", "iv": "S"}}'::jsonb WHERE id = 'b6fbcfcb-a859-467e-a655-4e4a6c33cb7e';

-- cuet-acc-ratio-solv-20: Match the solvency ratios with their formulas:  Column I: (i
UPDATE med_questions SET payload = payload || '{"column_a": [{"id": "i", "text": "Debt-Equity Ratio"}, {"id": "ii", "text": "Total Assets to Debt Ratio"}, {"id": "iii", "text": "Proprietary Ratio"}, {"id": "iv", "text": "Interest Coverage Ratio"}], "column_b": [{"id": "P", "text": "Shareholders'' Funds ÷ Total Assets"}, {"id": "Q", "text": "NPBIT ÷ Interest Expense"}, {"id": "R", "text": "Long-term Debt ÷ Shareholders'' Funds"}, {"id": "S", "text": "Total Assets ÷ Long-term Debt"}], "correct_mapping": {"i": "R", "ii": "S", "iii": "P", "iv": "Q"}}'::jsonb WHERE id = 'a570c442-8299-41db-8bf2-2b46ea92af2e';

-- cuet-acc-ratio-comp-18: Match the ratios with the stakeholder most interested:  Colu
UPDATE med_questions SET payload = payload || '{"column_a": [{"id": "i", "text": "Current Ratio"}, {"id": "ii", "text": "Debt-Equity Ratio"}, {"id": "iii", "text": "EPS"}, {"id": "iv", "text": "Inventory Turnover"}], "column_b": [{"id": "P", "text": "Equity Shareholders"}, {"id": "Q", "text": "Short-term Creditors"}, {"id": "R", "text": "Management"}, {"id": "S", "text": "Long-term Lenders"}], "correct_mapping": {"i": "Q", "ii": "S", "iii": "P", "iv": "R"}}'::jsonb WHERE id = 'b0de4b04-3a76-4597-bbb0-7b13a2e5a5aa';

-- Summary: 44 UPDATEs generated, 0 missing