#!/usr/bin/env python3
"""Generate the 40-question JSON for B04: Projection of Solids."""
import json, os

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "cuet-eg-solids-b04.json")

def base(qid, qtype, diff, bloom, subtopic, tags):
    return {
        "id": qid,
        "chapter_id": "cuet-eg-engineering-graphics",
        "topic_id": "cuet-eg-solids",
        "question_type": qtype,
        "difficulty": diff,
        "subject": "engineering-graphics",
        "chapter": "Engineering Graphics",
        "topic": "Projection of Solids",
        "subtopic": subtopic,
        "bloom_level": bloom,
        "exam_suitability": ["CUET"],
        "concept_tags": tags,
    }

def opt(k, t, c=False):
    return {"key": k, "text": t, "is_correct": c}

def hint(k, h, m=None):
    return {"option_key": k, "hint": h, "misconception": m}

def mcq(qid, diff, bloom, subtopic, tags, text, opts, correct, explanation, hints):
    q = base(qid, "mcq", diff, bloom, subtopic, tags)
    q.update({
        "question_text": text,
        "correct_answer": correct,
        "explanation": explanation,
        "options": opts,
        "elimination_hints": hints,
    })
    return q

def ar_q(qid, diff, bloom, subtopic, tags, assertion, reason, correct, explanation, hints_list):
    q = base(qid, "assertion-reasoning", diff, bloom, subtopic, tags)
    ar_opts = [
        opt("A", "Both A and R are true and R is the correct explanation of A"),
        opt("B", "Both A and R are true but R is NOT the correct explanation of A"),
        opt("C", "A is true but R is false"),
        opt("D", "A is false but R is true"),
    ]
    for o in ar_opts:
        if o["key"] == correct:
            o["is_correct"] = True
    q.update({
        "question_text": f"Assertion (A): {assertion}\nReason (R): {reason}",
        "assertion": assertion,
        "reason": reason,
        "correct_answer": correct,
        "explanation": explanation,
        "options": ar_opts,
        "elimination_hints": hints_list,
    })
    return q

def tf_q(qid, diff, subtopic, tags, text, correct_bool, explanation, hints_list):
    q = base(qid, "true-false", diff, "remember", subtopic, tags)
    q.update({
        "question_text": text,
        "correct_answer": "A" if correct_bool else "B",
        "explanation": explanation,
        "options": [
            opt("A", "True", correct_bool),
            opt("B", "False", not correct_bool),
            opt("C", "---"),
            opt("D", "---"),
        ],
        "elimination_hints": hints_list,
    })
    return q

questions = []

# ═══════════════════════════════════════════════════════════════════════════════
# MCQ — EASY (5): cuet-eg-solids-01 to 05
# ═══════════════════════════════════════════════════════════════════════════════

questions.append(mcq(
    "cuet-eg-solids-01", "easy", "remember", "Solid Classification",
    ["solid-types", "classification"],
    "Which of the following is a solid of revolution?",
    [opt("A", "Cube"),
     opt("B", "Triangular prism"),
     opt("C", "Cone", True),
     opt("D", "Hexagonal pyramid")],
    "C",
    "A cone is generated by revolving a right-angled triangle about one of its perpendicular sides. Solids of revolution include cones, cylinders, and spheres. Cubes, prisms, and pyramids are polyhedra (solids with flat faces).",
    [hint("A", "A cube is a polyhedron (6 flat faces), not a solid of revolution.", "Confusing polyhedra with solids of revolution"),
     hint("B", "A triangular prism has flat faces and is a polyhedron, not generated by revolution.", "Confusing prisms with revolution solids"),
     hint("D", "A hexagonal pyramid is a polyhedron with a hexagonal base and triangular faces.", "Confusing pyramids with revolution solids")]
))

questions.append(mcq(
    "cuet-eg-solids-02", "easy", "remember", "Prism Definition",
    ["prism", "definition"],
    "A prism is a solid with:",
    [opt("A", "Two identical parallel polygonal bases connected by rectangular lateral faces", True),
     opt("B", "A single polygonal base tapering to an apex"),
     opt("C", "Two circular bases connected by a curved surface"),
     opt("D", "A single circular base tapering to an apex")],
    "A",
    "A prism has two identical (congruent) parallel polygonal end faces connected by rectangular lateral faces. The lateral edges are parallel to the axis.",
    [hint("B", "A solid with a polygonal base tapering to an apex is a pyramid, not a prism.", "Confusing pyramid with prism"),
     hint("C", "Two circular bases connected by a curved surface describes a cylinder, not a prism.", "Confusing cylinder with prism"),
     hint("D", "A circular base tapering to an apex describes a cone, not a prism.", "Confusing cone with prism")]
))

questions.append(mcq(
    "cuet-eg-solids-03", "easy", "remember", "Axis Perpendicular to HP",
    ["axis-position", "perpendicular-hp"],
    "When the axis of a solid is perpendicular to the HP, the base of the solid is:",
    [opt("A", "Perpendicular to the HP"),
     opt("B", "Parallel to the HP", True),
     opt("C", "Inclined to the HP"),
     opt("D", "Parallel to the VP")],
    "B",
    "When the axis is perpendicular to HP, the base (which is perpendicular to the axis) lies parallel to HP. The top view shows the true shape of the base.",
    [hint("A", "If the base were perpendicular to HP, the axis would be parallel to HP, not perpendicular.", "Reversing the axis-base relationship"),
     hint("C", "If the base were inclined to HP, the axis would also be inclined (not perpendicular) to HP.", "Not understanding axis-base perpendicularity"),
     hint("D", "The base is parallel to HP, not necessarily to VP. The axis is perpendicular to HP.", "Confusing HP with VP")]
))

questions.append(mcq(
    "cuet-eg-solids-04", "easy", "remember", "Top View of Cylinder",
    ["cylinder", "top-view"],
    "The top view of a right circular cylinder resting on its base on the HP is:",
    [opt("A", "A rectangle"),
     opt("B", "An ellipse"),
     opt("C", "A circle", True),
     opt("D", "A triangle")],
    "C",
    "When a cylinder rests on its base on the HP, its axis is perpendicular to HP. The top view (projection on HP) shows the circular base as a circle.",
    [hint("A", "A rectangle is the front view of a cylinder with axis perpendicular to HP, not the top view.", "Confusing front view with top view"),
     hint("B", "An ellipse appears when the axis is inclined, not perpendicular, to the viewing plane.", "Applying inclined-axis rules to a vertical-axis case"),
     hint("D", "A triangle is the front view of a cone, not a cylinder.", "Confusing cone and cylinder front views")]
))

questions.append(mcq(
    "cuet-eg-solids-05", "easy", "remember", "Front View of Pyramid",
    ["pyramid", "front-view"],
    "The front view of a square pyramid resting on its base on the HP with a side of the base parallel to VP is:",
    [opt("A", "A square"),
     opt("B", "A circle"),
     opt("C", "A triangle", True),
     opt("D", "A pentagon")],
    "C",
    "When a square pyramid rests on its base on HP with a side parallel to VP, the front view shows a triangular outline — two slant edges meeting at the apex, with the base edge visible as a horizontal line.",
    [hint("A", "A square is the top view of the pyramid, not the front view.", "Confusing top view with front view"),
     hint("B", "A circle appears in the top view of a cone, not in the front view of a pyramid.", "Confusing different solids and views"),
     hint("D", "A pentagon has 5 sides. The front view of a square pyramid with side parallel to VP is a triangle (3-sided).", "Miscounting the visible edges")]
))

# ═══════════════════════════════════════════════════════════════════════════════
# MCQ — MEDIUM (10): cuet-eg-solids-06 to 15
# ═══════════════════════════════════════════════════════════════════════════════

questions.append(mcq(
    "cuet-eg-solids-06", "medium", "understand", "Prism Edge vs Face Parallel to VP",
    ["prism", "base-orientation"],
    "A hexagonal prism has its axis perpendicular to HP. If a side of the base is parallel to the VP, the front view will show:",
    [opt("A", "Three rectangular faces"),
     opt("B", "Two full rectangular faces and two half faces", True),
     opt("C", "One rectangular face only"),
     opt("D", "Six rectangular faces")],
    "B",
    "With a hexagonal base and one side parallel to VP, the front view shows two full rectangular faces (facing the observer directly) and two half (edge) faces on the sides, forming a wider rectangle. The remaining two faces are hidden.",
    [hint("A", "Three faces visible assumes the hexagon is oriented with a corner toward the viewer, not a side.", "Confusing side-parallel with corner-parallel orientation"),
     hint("C", "One face only would mean the hexagon is viewed perfectly edge-on from the front, which doesn't happen with side parallel to VP.", "Underestimating visible faces"),
     hint("D", "Six faces would require a transparent solid or an exploded view. Only the front-facing faces are visible.", "Not understanding hidden face concept")]
))

questions.append(mcq(
    "cuet-eg-solids-07", "medium", "understand", "Cone FV Height",
    ["cone", "front-view-dimensions"],
    "A cone with base radius 25 mm and height 50 mm rests on its base on HP. The front view is an isosceles triangle with base and height equal to:",
    [opt("A", "Base = 25 mm, Height = 50 mm"),
     opt("B", "Base = 50 mm, Height = 50 mm", True),
     opt("C", "Base = 25 mm, Height = 25 mm"),
     opt("D", "Base = 50 mm, Height = 25 mm")],
    "B",
    "The front view of a cone with axis perpendicular to HP is an isosceles triangle. The base of the triangle = diameter = 2 × 25 = 50 mm. The height of the triangle = height of the cone = 50 mm.",
    [hint("A", "25 mm is the radius, not the diameter. The base of the front view triangle is the full diameter (50 mm).", "Using radius instead of diameter"),
     hint("C", "Both values are wrong: base should be diameter (50 mm) and height should be cone height (50 mm).", "Using radius for both dimensions"),
     hint("D", "Height = 25 mm confuses the radius with the height. The height of the FV triangle equals the cone height.", "Swapping radius and height")]
))

questions.append(mcq(
    "cuet-eg-solids-08", "medium", "apply", "Axis Inclined to HP",
    ["inclined-axis", "two-step-method"],
    "When the axis of a solid is inclined to the HP, the first step in the two-step method is to draw the solid with its axis:",
    [opt("A", "Parallel to HP"),
     opt("B", "Perpendicular to VP"),
     opt("C", "Perpendicular to HP", True),
     opt("D", "Inclined at 45° to HP")],
    "C",
    "In the two-step method for a solid with axis inclined to HP: Step 1 draws the solid with axis perpendicular to HP (giving the true base shape in the top view). Step 2 tilts the front view to the required angle with HP.",
    [hint("A", "Axis parallel to HP means the solid is lying on its side. This is not the standard starting position for the two-step method.", "Confusing parallel with perpendicular"),
     hint("B", "Perpendicular to VP is the starting position when the axis is inclined to VP, not to HP.", "Applying the VP method to an HP problem"),
     hint("D", "Starting at 45° doesn't simplify the construction. The standard first step uses axis ⊥ HP for the true base shape.", "Not understanding the purpose of Step 1")]
))

questions.append(mcq(
    "cuet-eg-solids-09", "medium", "apply", "Slant Height Calculation",
    ["pyramid", "slant-height"],
    "A square pyramid has a base side of 40 mm and axis height of 60 mm. The slant height of its triangular face is:",
    [opt("A", "60 mm"),
     opt("B", "72.11 mm"),
     opt("C", "63.25 mm", True),
     opt("D", "50 mm")],
    "C",
    "Slant height of a triangular face = distance from apex to midpoint of base edge. The midpoint of a base edge is at distance (side/2) = 20 mm from the axis. Slant height = sqrt(60² + 20²) = sqrt(3600 + 400) = sqrt(4000) = 63.25 mm.",
    [hint("A", "60 mm is the axis height, not the slant height. The slant height is longer because it goes from apex to the base edge (not to the base center).", "Using axis height as slant height"),
     hint("B", "72.11 mm = sqrt(60² + 40²) uses the full base side (40 mm) instead of the apothem (20 mm). The slant height goes to the midpoint of the edge.", "Using base side instead of half-side"),
     hint("D", "50 mm doesn't correspond to any standard calculation for this pyramid.", "Incorrect calculation")]
))

questions.append(mcq(
    "cuet-eg-solids-10", "medium", "understand", "Visible and Hidden Edges",
    ["visible-edges", "hidden-edges"],
    "In the front view of a pentagonal prism with axis perpendicular to HP and one face parallel to VP, the hidden edges are shown as:",
    [opt("A", "Continuous thick lines"),
     opt("B", "Dashed (hidden) lines", True),
     opt("C", "Chain lines"),
     opt("D", "They are not shown at all")],
    "B",
    "Edges that are behind the visible surface (not directly visible to the observer) are shown as dashed lines (hidden lines) in engineering drawing convention. This is a fundamental drafting rule.",
    [hint("A", "Continuous thick lines represent visible outlines, not hidden edges.", "Confusing visible and hidden line types"),
     hint("C", "Chain lines (dash-dot) represent center lines and axes, not hidden edges.", "Confusing center lines with hidden lines"),
     hint("D", "Hidden edges must be shown (as dashed lines) for complete representation of the solid.", "Ignoring hidden edge convention")]
))

questions.append(mcq(
    "cuet-eg-solids-11", "medium", "apply", "Pyramid TV with Corner Forward",
    ["pyramid", "base-orientation"],
    "A square pyramid rests on HP with its axis perpendicular to HP. If a corner of the base (not a side) is nearest to the observer (toward VP), the top view will show the square base with:",
    [opt("A", "A side parallel to XY"),
     opt("B", "A diagonal parallel to XY", True),
     opt("C", "A side at 45° to XY"),
     opt("D", "All sides at equal angles to XY")],
    "B",
    "When a corner of the square is nearest to the observer (VP), the diagonal connecting that corner to the opposite one is perpendicular to VP, meaning the other diagonal is parallel to XY. The top view shows the square rotated 45° with a diagonal parallel to XY.",
    [hint("A", "A side parallel to XY means a side (not a corner) faces the VP. This contradicts the 'corner nearest' condition.", "Confusing side-facing with corner-facing"),
     hint("C", "45° to XY would be an intermediate case. With a corner forward, one diagonal is parallel to XY.", "Not fully analyzing the corner-forward orientation"),
     hint("D", "A square has sides at different angles to XY depending on orientation. They cannot all be at equal angles (that would require more than 4 sides).", "Geometrically impossible for a square")]
))

questions.append(mcq(
    "cuet-eg-solids-12", "medium", "apply", "Cylinder Axis Parallel to VP",
    ["cylinder", "axis-parallel-vp"],
    "A right circular cylinder has its axis parallel to both HP and VP. Its front view and top view are respectively:",
    [opt("A", "Circle and rectangle"),
     opt("B", "Rectangle and circle"),
     opt("C", "Circle and circle"),
     opt("D", "Rectangle and rectangle", True)],
    "D",
    "When the axis is parallel to both HP and VP (perpendicular to the profile plane), the front view shows a rectangle (height = length, width = diameter) and the top view also shows a rectangle (length × diameter). The side view shows the circle.",
    [hint("A", "A circle in the front view would require the axis to be perpendicular to VP. Here the axis is parallel to VP.", "Confusing perpendicular and parallel to VP"),
     hint("B", "A circle in the top view would require the axis to be perpendicular to HP. Here the axis is parallel to HP.", "Confusing perpendicular and parallel to HP"),
     hint("C", "Circles in both views would require the axis to be simultaneously perpendicular to both HP and VP, which is impossible.", "Geometrically impossible axis orientation")]
))

questions.append(mcq(
    "cuet-eg-solids-13", "medium", "apply", "Tetrahedron Projection",
    ["tetrahedron", "projection"],
    "A regular tetrahedron rests on one face on the HP. The top view of this tetrahedron is:",
    [opt("A", "An equilateral triangle with the apex at the centroid", True),
     opt("B", "A square"),
     opt("C", "A circle"),
     opt("D", "A regular hexagon")],
    "A",
    "A regular tetrahedron has 4 equilateral triangular faces. When resting on one face on HP, the top view shows the triangular base with the projection of the apex at the centroid of the triangle (since the apex is directly above the centroid).",
    [hint("B", "A square top view belongs to a cube or square-based solid, not a tetrahedron.", "Confusing tetrahedron with cube"),
     hint("C", "A circle appears in the top view of cones or cylinders, not tetrahedra.", "Confusing solid types"),
     hint("D", "A hexagonal top view belongs to hexagonal prisms or pyramids, not tetrahedra.", "Confusing solid types")]
))

questions.append(mcq(
    "cuet-eg-solids-14", "medium", "understand", "Axis Inclined to Both Planes",
    ["axis-inclined-both", "three-step"],
    "When the axis of a solid is inclined to both HP and VP, the minimum number of steps required in the change-of-position method is:",
    [opt("A", "One"),
     opt("B", "Two"),
     opt("C", "Three", True),
     opt("D", "Four")],
    "C",
    "When the axis is inclined to both planes: Step 1 draws the solid with axis ⊥ HP (true base in TV). Step 2 tilts to set the HP angle. Step 3 tilts to set the VP angle. Three steps are needed because both inclinations cannot be set simultaneously.",
    [hint("A", "One step suffices only when the axis is already perpendicular to one plane.", "Underestimating the construction complexity"),
     hint("B", "Two steps handle inclination to one plane. For inclination to both, a third step is needed.", "Forgetting the VP angle step"),
     hint("D", "Four steps are not needed. Three steps (true position + two tilts) are sufficient.", "Overestimating the number of steps")]
))

questions.append(mcq(
    "cuet-eg-solids-15", "medium", "apply", "Prism Axis Parallel to HP",
    ["prism", "axis-parallel-hp"],
    "A triangular prism has its axis parallel to HP and perpendicular to VP. Its front view will be:",
    [opt("A", "A rectangle"),
     opt("B", "A triangle", True),
     opt("C", "A hexagon"),
     opt("D", "A circle")],
    "B",
    "When the axis is perpendicular to VP, the front view shows the true shape of the cross-section (base). For a triangular prism, this is a triangle. The top view shows a rectangle.",
    [hint("A", "A rectangle is the top view (or side view) of this prism, not the front view with axis ⊥ VP.", "Confusing which view shows which shape"),
     hint("C", "A hexagonal front view would require a hexagonal prism or a special orientation, not a triangular prism.", "Wrong solid type"),
     hint("D", "A circle front view appears for a cylinder with axis ⊥ VP, not for a prism.", "Confusing prism with cylinder")]
))

# ═══════════════════════════════════════════════════════════════════════════════
# MCQ — HARD (5): cuet-eg-solids-16 to 20
# ═══════════════════════════════════════════════════════════════════════════════

questions.append(mcq(
    "cuet-eg-solids-16", "hard", "analyze", "Apparent Base Shape",
    ["apparent-shape", "inclined-axis"],
    "A regular hexagonal prism with axis inclined at 30° to HP and parallel to VP rests on one of its rectangular faces on HP. The top view of the hexagonal base will appear as:",
    [opt("A", "A regular hexagon"),
     opt("B", "An irregular hexagon (foreshortened)", True),
     opt("C", "A rectangle"),
     opt("D", "A straight line")],
    "B",
    "When the axis is inclined to HP, the hexagonal base (which is perpendicular to the axis) is also inclined to HP. Its top view is foreshortened — the dimension along the inclination is compressed by cos 30°, producing an irregular (non-regular) hexagon.",
    [hint("A", "A regular hexagon in TV requires the base to be parallel to HP (axis ⊥ HP). With inclined axis, the TV is foreshortened.", "Ignoring foreshortening due to axis inclination"),
     hint("C", "A rectangle is not the shape of a foreshortened hexagon. Hexagons remain six-sided in projection.", "Changing the number of sides in projection"),
     hint("D", "A straight line (edge view) occurs only when the base is perpendicular to HP, not when it's inclined.", "Confusing inclined with perpendicular")]
))

questions.append(mcq(
    "cuet-eg-solids-17", "hard", "apply", "Slant Edge of Pyramid",
    ["pyramid", "slant-edge-calculation"],
    "A pentagonal pyramid has a base side of 30 mm and axis height of 50 mm. The true length of its slant edge (from apex to a base corner) is closest to:",
    [opt("A", "58.3 mm"),
     opt("B", "50 mm"),
     opt("C", "55.5 mm"),
     opt("D", "54.1 mm", True)],
    "D",
    "The circumradius of a regular pentagon with side 30 mm = 30/(2 sin(36°)) = 30/(2 × 0.5878) = 25.52 mm. Slant edge = sqrt(50² + 25.52²) = sqrt(2500 + 651.3) = sqrt(3151.3) = 56.1 mm. Wait, let me recalculate: circumradius R = a/(2 sin(pi/5)) = 30/(2 × 0.5878) = 25.52. Slant edge = sqrt(50² + 25.52²) = sqrt(2500 + 651) = sqrt(3151) = 56.1. Hmm, closest is A (58.3). Let me recheck: actually R = a/(2 sin(pi/n)) = 30/(2 sin(36°)) = 30/1.1756 = 25.52. sqrt(2500+651.3) = sqrt(3151.3) = 56.14. None match exactly. Let me adjust: using the formula for pentagon circumradius = side × 0.851 = 30 × 0.851 = 25.53. sqrt(2500+651.6) ≈ 56.1. Closest option would be 55.5 or 58.3. Actually 54.1 = sqrt(50²+20²) if using apothem incorrectly. Let me pick a cleaner example and make D = 56.1.",
    [hint("A", "58.3 mm would require a larger base radius. Check: this might use the wrong circumradius formula.", "Using incorrect circumradius"),
     hint("B", "50 mm is the axis height, not the slant edge. The slant edge extends from apex to a corner, not to the center.", "Using axis height as slant edge"),
     hint("C", "55.5 mm is close but uses an approximate circumradius. The exact value is sqrt(50² + R²).", "Approximation error")]
))

# Fix Q17 to use clean numbers
questions[-1]["question_text"] = "A square pyramid has a base side of 40 mm and axis height of 50 mm. The true length of its slant edge (from apex to a base corner) is closest to:"
questions[-1]["explanation"] = "For a square with side 40 mm, the half-diagonal = (40√2)/2 = 28.28 mm. This is the distance from the center to a corner. Slant edge = sqrt(50² + 28.28²) = sqrt(2500 + 800) = sqrt(3300) = 57.45 mm."
questions[-1]["options"] = [
    opt("A", "64 mm"),
    opt("B", "50 mm"),
    opt("C", "63.25 mm"),
    opt("D", "57.45 mm", True),
]
questions[-1]["elimination_hints"] = [
    hint("A", "64 mm = sqrt(50² + 40²) uses the full side length instead of the half-diagonal as the base radius.", "Using side instead of half-diagonal"),
    hint("B", "50 mm is the axis height. The slant edge goes from apex to a corner, which is farther than the base center.", "Confusing axis height with slant edge"),
    hint("C", "63.25 mm = sqrt(50² + 40²) uses the wrong distance. The distance from center to corner is half-diagonal (28.28 mm), not the full side.", "Using wrong reference distance"),
]

questions.append(mcq(
    "cuet-eg-solids-18", "hard", "analyze", "Generator of Cone in FV",
    ["cone", "generator-projection"],
    "A cone rests on HP with its axis perpendicular to HP. A generator on the surface of the cone that is parallel to the VP will appear in the front view as:",
    [opt("A", "A straight line showing its true length", True),
     opt("B", "A curved line"),
     opt("C", "A point"),
     opt("D", "A line shorter than the true length")],
    "A",
    "A generator is a straight line on the cone's surface from apex to base circle. If this generator is parallel to VP, its front view (projection on VP) shows its true length as a straight line. It appears as one of the slant edges of the triangular front view.",
    [hint("B", "Generators are straight lines on the cone surface. They always project as straight lines, never curves.", "Confusing generators with base circle projection"),
     hint("C", "A point projection occurs for a line perpendicular to the viewing plane. A generator parallel to VP projects as a line, not a point.", "Confusing parallel with perpendicular"),
     hint("D", "Since the generator is parallel to VP, there is no foreshortening in the front view. The true length is visible.", "Applying foreshortening to a parallel line")]
))

questions.append(mcq(
    "cuet-eg-solids-19", "hard", "evaluate", "Projection Ambiguity",
    ["projection-ambiguity", "multiple-solids"],
    "Which of the following pairs of solids can have identical front views (both showing a rectangle of the same dimensions) when their axes are perpendicular to the HP?",
    [opt("A", "Cone and cylinder"),
     opt("B", "Cylinder and square prism", True),
     opt("C", "Cone and pyramid"),
     opt("D", "Sphere and cube")],
    "B",
    "A cylinder (diameter = d, height = h) has FV as a rectangle (d × h). A square prism (side = d, height = h) also has FV as a rectangle (d × h) when a face is parallel to VP. Both produce identical rectangular front views despite being different solids.",
    [hint("A", "A cone has a triangular FV while a cylinder has a rectangular FV. They cannot be identical.", "Confusing triangular with rectangular FV"),
     hint("C", "A cone has a triangular FV and a pyramid also has a triangular FV, but the shapes may differ in slant edge curvature vs straight edges. They don't both give rectangles.", "Both triangular, not rectangular"),
     hint("D", "A sphere has a circular FV. A cube has a square (or rectangular) FV. These are never identical.", "Confusing circular with rectangular projections")]
))

questions.append(mcq(
    "cuet-eg-solids-20", "hard", "evaluate", "Solid on Inclined Face",
    ["solid-on-face", "inclined-position"],
    "A cube rests on one of its faces on the HP. The axis of the cube makes an angle with the HP equal to:",
    [opt("A", "0°"),
     opt("B", "45°"),
     opt("C", "90°", True),
     opt("D", "60°")],
    "C",
    "A cube resting on a face has that face parallel to HP. The axis of a cube (line joining centers of two opposite faces) is perpendicular to any face. Therefore, the axis is perpendicular to HP, making an angle of 90° with HP.",
    [hint("A", "0° would mean the axis is parallel to HP, implying the cube rests on an edge, not a face.", "Confusing resting on face with resting on edge"),
     hint("B", "45° would mean the cube is tilted. When resting squarely on a face, the axis is vertical (90°).", "Imagining a tilted cube"),
     hint("D", "60° has no special significance for a cube resting on a face. The axis is perpendicular (90°) to the base face.", "Guessing without geometric reasoning")]
))

# ═══════════════════════════════════════════════════════════════════════════════
# DIAGRAM-BASED (4): cuet-eg-solids-21 to 24
# ═══════════════════════════════════════════════════════════════════════════════

q21 = base("cuet-eg-solids-21", "diagram-based", "easy", "apply", "Solid Identification", ["solid-identification", "axis-vertical"])
q21.update({
    "question_text": "From the figure showing two solids with axes perpendicular to HP, identify the top view of the square pyramid.",
    "correct_answer": "D",
    "explanation": "The right side of the diagram shows a square pyramid. Its top view (below XY) is a square with diagonals drawn from each corner to the center point 'o' (apex projection). The diagonals represent the slant edges of the pyramid.",
    "image_uri": "question-images/engineering-graphics/solids/cuet-eg-solids-41-axis-vertical.png",
    "image_alt": "Two solids with axis perpendicular to HP: left shows pentagonal prism (FV=rectangle, TV=pentagon), right shows square pyramid (FV=triangle, TV=square with diagonals).",
    "options": [
        opt("A", "A pentagon with internal lines"),
        opt("B", "A rectangle"),
        opt("C", "A circle with center point"),
        opt("D", "A square with diagonals meeting at center 'o'", True),
    ],
    "elimination_hints": [
        hint("A", "The pentagon is the top view of the pentagonal prism (left solid), not the square pyramid.", "Confusing the two solids in the diagram"),
        hint("B", "A rectangle is the front view of a prism, not the top view of a pyramid.", "Confusing front view with top view"),
        hint("C", "A circle with center is the top view of a cone or cylinder, not a pyramid.", "Confusing cone/cylinder with pyramid"),
    ]
})
questions.append(q21)

q22 = base("cuet-eg-solids-22", "diagram-based", "easy", "apply", "Cone Dimensions", ["cone", "dimension-reading"])
q22.update({
    "question_text": "From the figure showing a cone with axis perpendicular to HP, the front view is a triangle. What does the dimension 'r' marked in the diagram represent?",
    "correct_answer": "B",
    "explanation": "In the diagram, 'r' is marked as the horizontal distance from the axis to the base edge in the front view. This represents the base radius of the cone. The full base width of the triangular FV is the diameter (2r).",
    "image_uri": "question-images/engineering-graphics/solids/cuet-eg-solids-42-cone-vertical.png",
    "image_alt": "Cone with axis perpendicular to HP: FV is an isosceles triangle with height h and base 2r, TV is a circle of radius r with apex at center o.",
    "options": [
        opt("A", "The slant height of the cone"),
        opt("B", "The base radius of the cone", True),
        opt("C", "The height of the cone"),
        opt("D", "The diameter of the cone"),
    ],
    "elimination_hints": [
        hint("A", "The slant height is the length of the slant edge (from apex to base circle), not the horizontal dimension r.", "Confusing slant height with radius"),
        hint("C", "The height is marked as 'h' (vertical dimension). The radius 'r' is the horizontal dimension.", "Swapping h and r"),
        hint("D", "The diameter is 2r. The mark 'r' goes from the center to the edge, which is the radius.", "Confusing radius with diameter"),
    ]
})
questions.append(q22)

q23 = base("cuet-eg-solids-23", "diagram-based", "medium", "analyze", "Cylinder Inclined Axis", ["cylinder", "inclined-axis"])
q23.update({
    "question_text": "The figure shows a cylinder projected using the two-step method. In Step 2, the axis is inclined at 30 degrees to HP. The top view of the inclined cylinder is:",
    "correct_answer": "A",
    "explanation": "When a cylinder's axis is inclined to HP, the circular base becomes inclined to the horizontal. The top view changes from a circle (Step 1) to an elongated shape — a rectangle with semicircular ends (stadium/oblong shape), as the cylinder's length projects onto the horizontal plane.",
    "image_uri": "question-images/engineering-graphics/solids/cuet-eg-solids-43-cylinder-inclined.png",
    "image_alt": "Two-step method for cylinder: Step 1 shows axis perp to HP (FV=rectangle, TV=circle). Step 2 shows axis at 30 degrees (FV=tilted rectangle, TV=elongated rounded shape).",
    "options": [
        opt("A", "An elongated shape with rounded ends (stadium/oblong)", True),
        opt("B", "A perfect circle"),
        opt("C", "An ellipse"),
        opt("D", "A rectangle"),
    ],
    "elimination_hints": [
        hint("B", "A perfect circle is the top view only when the axis is perpendicular to HP (Step 1). In Step 2, the axis is inclined.", "Applying Step 1 result to Step 2"),
        hint("C", "An ellipse is the projection of just the circular base. The full cylinder top view includes the body length, giving a rounded-rectangle shape.", "Projecting only the base, not the full solid"),
        hint("D", "A plain rectangle ignores the circular ends. The top view has rounded (semicircular) ends from the base circles.", "Ignoring the circular cross-section"),
    ]
})
questions.append(q23)

q24 = base("cuet-eg-solids-24", "diagram-based", "hard", "evaluate", "Three-Step Pyramid", ["pyramid", "three-step-method"])
q24.update({
    "question_text": "The figure shows the three-step method for a hexagonal pyramid with axis inclined to both HP and VP. In Step 2, the front view is tilted to set the angle with HP. What happens to the hexagonal top view in Step 2?",
    "correct_answer": "C",
    "explanation": "In Step 2, when the front view is tilted to set the HP angle, the top view changes from a regular hexagon (true base shape from Step 1) to a foreshortened hexagon. The dimension along the tilt direction is compressed, while the perpendicular dimension remains unchanged.",
    "image_uri": "question-images/engineering-graphics/solids/cuet-eg-solids-44-pyramid-inclined-both.png",
    "image_alt": "Three-step method for hexagonal pyramid: Step 1 (axis perp HP, regular hex TV), Step 2 (FV tilted, foreshortened hex TV), Step 3 (TV tilted, apparent shapes in both views).",
    "options": [
        opt("A", "It remains a regular hexagon"),
        opt("B", "It becomes a straight line"),
        opt("C", "It becomes a foreshortened (irregular) hexagon", True),
        opt("D", "It disappears"),
    ],
    "elimination_hints": [
        hint("A", "A regular hexagon requires the base to be parallel to HP. Tilting the FV changes the base orientation, foreshortening the TV.", "Ignoring the effect of tilting on the top view"),
        hint("B", "A straight line would mean the base becomes perpendicular to HP, which happens only at 90° tilt, not at intermediate angles.", "Confusing intermediate tilt with 90° tilt"),
        hint("D", "The top view never disappears. It is always present as a projection on HP, though it may be foreshortened.", "Misunderstanding projection fundamentals"),
    ]
})
questions.append(q24)

# ═══════════════════════════════════════════════════════════════════════════════
# ASSERTION-REASONING (4): cuet-eg-solids-25 to 28
# ═══════════════════════════════════════════════════════════════════════════════

questions.append(ar_q(
    "cuet-eg-solids-25", "medium", "understand", "Axis and Base Relationship",
    ["axis", "base-perpendicular"],
    "The axis of a right solid is always perpendicular to its base.",
    "In a right solid, the axis connects the center of the base to the apex (for pyramids/cones) or to the center of the opposite base (for prisms/cylinders), and this connection is perpendicular to the base.",
    "A",
    "Both A and R are true, and R correctly explains A. By definition, a 'right' solid has its axis perpendicular to the base. This distinguishes right solids from oblique solids where the axis is inclined to the base.",
    [hint("B", "R directly explains A — the perpendicularity of the axis to the base is the defining characteristic of a 'right' solid.", "Failing to see the definitional relationship"),
     hint("C", "R is true — it correctly describes how the axis relates to the base in a right solid.", "Rejecting a correct geometric definition"),
     hint("D", "A is true — all right solids (right prisms, right pyramids, right cylinders, right cones) have axes perpendicular to their bases.", "Rejecting the definition of right solids")]
))

questions.append(ar_q(
    "cuet-eg-solids-26", "medium", "understand", "TV Shows True Base",
    ["top-view", "true-base-shape"],
    "When a solid rests on its base on the HP with its axis perpendicular to HP, the top view shows the true shape of its base.",
    "The base is parallel to HP when the axis is perpendicular to HP, and a plane parallel to HP projects its true shape in the top view.",
    "A",
    "Both are true and R correctly explains A. When axis ⊥ HP, base ∥ HP, so the projection on HP (top view) shows the base in its true shape without foreshortening.",
    [hint("B", "R directly explains A — the parallelism of the base to HP is the reason the top view shows the true shape.", "Not connecting parallelism with true shape"),
     hint("C", "R is true — it correctly states the projection principle for parallel planes.", "Rejecting a fundamental projection principle"),
     hint("D", "A is true — this is the basis of the first step in the change-of-position method.", "Rejecting a core solid projection principle")]
))

questions.append(ar_q(
    "cuet-eg-solids-27", "hard", "analyze", "Oblique Solid Projection",
    ["oblique-solid", "axis-inclination"],
    "The front view of an oblique cone resting on its base on HP shows an isosceles triangle.",
    "In an oblique cone, the axis is not perpendicular to the base, causing the apex to be off-center when viewed from the front.",
    "D",
    "A is false — the front view of an oblique cone is a scalene (asymmetric) triangle, not an isosceles triangle, because the apex is off-center. R is true — the axis of an oblique cone is not perpendicular to the base, placing the apex off-center. So A is false, R is true.",
    [hint("A", "An isosceles triangle appears only for a RIGHT cone. An oblique cone has an off-center apex, giving a scalene triangle.", "Applying right-cone rules to oblique cones"),
     hint("B", "A is false (the FV is scalene, not isosceles). You cannot select 'both true' when A is false.", "Not recognizing the false assertion"),
     hint("C", "R is true — the off-center axis is the defining feature of an oblique cone.", "Rejecting the correct reason")]
))

questions.append(ar_q(
    "cuet-eg-solids-28", "hard", "analyze", "Number of Steps for Projection",
    ["change-of-position", "step-count"],
    "A solid with its axis inclined to HP and parallel to VP requires a three-step change-of-position method.",
    "The three-step method is needed when the axis is inclined to both HP and VP.",
    "D",
    "A is false — when the axis is inclined to HP but parallel to VP, only a two-step method is needed (Step 1: axis ⊥ HP, Step 2: tilt to HP angle). Three steps are needed only when inclined to BOTH planes. R is true — it correctly states when three steps are needed.",
    [hint("A", "A requires only two steps, not three. Three steps are for axes inclined to BOTH planes, not just one.", "Overstating the number of steps for single-plane inclination"),
     hint("B", "A is false (two steps suffice for single-plane inclination). Both cannot be true.", "Accepting the false assertion"),
     hint("C", "R is true — the three-step method is specifically for dual-plane axis inclination.", "Rejecting the correct reason")]
))

# ═══════════════════════════════════════════════════════════════════════════════
# MATCH-THE-FOLLOWING (2): cuet-eg-solids-29 to 30
# ═══════════════════════════════════════════════════════════════════════════════

q29 = base("cuet-eg-solids-29", "match-the-following", "medium", "understand", "Solids and Their Top Views", ["solid-types", "top-view-shapes"])
q29.update({
    "question_text": "Match the solid (axis ⊥ HP) with its TOP VIEW:\n\nColumn A: (P) Right circular cylinder, (Q) Hexagonal prism, (R) Square pyramid, (S) Right circular cone\nColumn B: (1) Circle with center point, (2) Regular hexagon, (3) Circle, (4) Square with diagonals",
    "correct_answer": "C",
    "explanation": "Cylinder: TV = circle (P-3). Hex prism: TV = regular hexagon (Q-2). Square pyramid: TV = square with diagonals to center (R-4). Cone: TV = circle with center point (S-1, the center point is the apex projection).",
    "column_a": ["Right circular cylinder", "Hexagonal prism", "Square pyramid", "Right circular cone"],
    "column_b": ["Circle with center point", "Regular hexagon", "Circle", "Square with diagonals"],
    "correct_mapping": {"Right circular cylinder": "Circle", "Hexagonal prism": "Regular hexagon", "Square pyramid": "Square with diagonals", "Right circular cone": "Circle with center point"},
    "options": [
        opt("A", "P-1, Q-2, R-4, S-3"),
        opt("B", "P-3, Q-2, R-1, S-4"),
        opt("C", "P-3, Q-2, R-4, S-1", True),
        opt("D", "P-1, Q-4, R-2, S-3"),
    ],
    "elimination_hints": [
        hint("A", "P-1 gives cylinder a 'circle with center point'. A cylinder has no apex, so no center point is needed. The cone needs the center point (apex).", "Confusing cylinder with cone"),
        hint("B", "R-1 gives pyramid a 'circle with center point'. A pyramid has a polygonal base, not a circular one.", "Confusing pyramid with cone"),
        hint("D", "Q-4 gives hexagonal prism a 'square with diagonals'. The hex prism has a hexagonal base, not square.", "Mismatching base shapes"),
    ]
})
questions.append(q29)

q30 = base("cuet-eg-solids-30", "match-the-following", "hard", "analyze", "Solid Axis Positions and Views", ["axis-orientation", "front-view-shapes"])
q30.update({
    "question_text": "Match the cone orientation with its FRONT VIEW:\n\nColumn A: (P) Axis ⊥ HP, (Q) Axis ⊥ VP, (R) Axis ∥ HP and ∥ VP, (S) Axis inclined at 45° to HP, ∥ VP\nColumn B: (1) Circle, (2) Isosceles triangle, (3) Tilted triangle (apex shifted), (4) Isosceles triangle (horizontal axis)",
    "correct_answer": "A",
    "explanation": "Axis ⊥ HP: FV = upright isosceles triangle (P-2). Axis ⊥ VP: FV = circle (Q-1). Axis ∥ HP and ∥ VP: FV = horizontal isosceles triangle (R-4). Axis at 45° to HP, ∥ VP: FV = tilted triangle (S-3).",
    "column_a": ["Axis ⊥ HP", "Axis ⊥ VP", "Axis ∥ HP and ∥ VP", "Axis at 45° to HP, ∥ VP"],
    "column_b": ["Circle", "Isosceles triangle (upright)", "Tilted triangle (apex shifted)", "Isosceles triangle (horizontal axis)"],
    "correct_mapping": {"Axis ⊥ HP": "Isosceles triangle (upright)", "Axis ⊥ VP": "Circle", "Axis ∥ HP and ∥ VP": "Isosceles triangle (horizontal axis)", "Axis at 45° to HP, ∥ VP": "Tilted triangle (apex shifted)"},
    "options": [
        opt("A", "P-2, Q-1, R-4, S-3", True),
        opt("B", "P-1, Q-2, R-4, S-3"),
        opt("C", "P-2, Q-1, R-3, S-4"),
        opt("D", "P-2, Q-3, R-1, S-4"),
    ],
    "elimination_hints": [
        hint("B", "P-1 says axis ⊥ HP gives a circle in FV. But axis ⊥ HP means the cone is upright, giving a triangle FV. The circle FV requires axis ⊥ VP.", "Swapping P and Q results"),
        hint("C", "R-3 says axis ∥ both planes gives a tilted triangle. But with horizontal axis, the triangle is symmetric (not tilted). Tilting occurs when inclined to HP.", "Confusing horizontal with tilted"),
        hint("D", "Q-3 says axis ⊥ VP gives a tilted triangle. But ⊥ VP means viewing along the axis, giving a circle.", "Not understanding end-on view"),
    ]
})
questions.append(q30)

# ═══════════════════════════════════════════════════════════════════════════════
# TRUE-FALSE (4): cuet-eg-solids-31 to 34
# ═══════════════════════════════════════════════════════════════════════════════

questions.append(tf_q(
    "cuet-eg-solids-31", "easy", "Solid of Revolution",
    ["cylinder", "revolution"],
    "A right circular cylinder can be generated by revolving a rectangle about one of its sides.",
    True,
    "When a rectangle is revolved about one of its sides (used as the axis), the opposite side traces a circular path, generating a right circular cylinder. The axis side becomes the axis of the cylinder.",
    [hint("B", "Revolving a rectangle about one side creates a cylinder: the parallel side traces a circle (base), and the perpendicular sides trace the curved surface.", "Not visualizing the rotation")]
))

questions.append(tf_q(
    "cuet-eg-solids-32", "easy", "Prism Lateral Face",
    ["prism", "lateral-faces"],
    "All lateral faces of a right prism are rectangular.",
    True,
    "In a right prism, the lateral edges are perpendicular to the base. This makes all lateral faces rectangles (each formed by two adjacent base edges and two parallel lateral edges).",
    [hint("B", "In a RIGHT prism, lateral edges are ⊥ base, so each lateral face has four right angles — making it a rectangle. Oblique prisms have parallelogram faces.", "Confusing right and oblique prisms")]
))

questions.append(tf_q(
    "cuet-eg-solids-33", "medium", "Cone Generator",
    ["cone", "generator"],
    "All generators of a right circular cone are of equal length.",
    True,
    "In a right circular cone, the apex is directly above the center of the circular base. All generators (lines from apex to points on the base circle) have the same length = sqrt(h² + r²), the slant height.",
    [hint("B", "In a RIGHT cone, the apex is at equal distance from all base circle points. Therefore all generators = slant height = sqrt(h² + r²).", "Confusing right and oblique cones")]
))

questions.append(tf_q(
    "cuet-eg-solids-34", "medium", "Pyramid Base Edges",
    ["pyramid", "projection-edges"],
    "When a pyramid rests on its base on HP, all base edges are visible in the top view as true lengths.",
    True,
    "When the base is on HP (parallel to HP), the top view shows the true shape of the base. All base edges, being in a plane parallel to HP, appear as true lengths in the top view.",
    [hint("B", "The base lies on (parallel to) HP. Edges in a plane parallel to HP project as true lengths in the top view. This is a fundamental projection rule.", "Forgetting that edges parallel to HP show true length in TV")]
))

# ═══════════════════════════════════════════════════════════════════════════════
# FILL-IN-BLANKS (2): cuet-eg-solids-35 to 36
# ═══════════════════════════════════════════════════════════════════════════════

q35 = base("cuet-eg-solids-35", "fill-in-blanks", "easy", "remember", "Solid Axis Definition", ["axis", "terminology"])
q35.update({
    "question_text": "The imaginary line connecting the center of the base to the apex of a pyramid is called the _____ of the pyramid.",
    "text_with_blanks": "The imaginary line connecting the center of the base to the apex of a pyramid is called the _____ of the pyramid.",
    "correct_answer": "B",
    "explanation": "The axis of a pyramid is the imaginary straight line joining the center of the base to the apex. For a right pyramid, the axis is perpendicular to the base.",
    "options": [
        opt("A", "Generator"),
        opt("B", "Axis", True),
        opt("C", "Slant edge"),
        opt("D", "Lateral edge"),
    ],
    "elimination_hints": [
        hint("A", "A generator is a line on the surface of a cone (from apex to base circle), not the center line of a pyramid.", "Confusing cone terminology with pyramid terminology"),
        hint("C", "A slant edge goes from the apex to a corner of the base, not to the center.", "Confusing slant edge with axis"),
        hint("D", "A lateral edge is the same as a slant edge for a pyramid — it goes from apex to a base corner, not to the center.", "Using an alternative name for slant edge"),
    ]
})
questions.append(q35)

q36 = base("cuet-eg-solids-36", "fill-in-blanks", "medium", "understand", "FV of Prism", ["prism", "front-view"])
q36.update({
    "question_text": "The front view of a pentagonal prism with axis perpendicular to HP and one rectangular face parallel to VP is a _____.",
    "text_with_blanks": "The front view of a pentagonal prism with axis perpendicular to HP and one rectangular face parallel to VP is a _____.",
    "correct_answer": "D",
    "explanation": "When a pentagonal prism has axis ⊥ HP and one rectangular face ∥ VP, the front view shows that face as a rectangle plus visible portions of adjacent faces, forming an overall rectangular outline.",
    "options": [
        opt("A", "Pentagon"),
        opt("B", "Circle"),
        opt("C", "Triangle"),
        opt("D", "Rectangle", True),
    ],
    "elimination_hints": [
        hint("A", "A pentagon is the top view (base shape), not the front view of a prism with vertical axis.", "Confusing top and front views"),
        hint("B", "A circle is the front view of a cylinder, not a prism.", "Confusing prism with cylinder"),
        hint("C", "A triangle is the front view of a pyramid or cone, not a prism.", "Confusing prism with pyramid"),
    ]
})
questions.append(q36)

# ═══════════════════════════════════════════════════════════════════════════════
# SCENARIO-BASED (2): cuet-eg-solids-37 to 38
# ═══════════════════════════════════════════════════════════════════════════════

q37 = base("cuet-eg-solids-37", "scenario-based", "medium", "apply", "Water Tank Projection", ["real-world", "cylinder-projection"])
q37.update({
    "question_text": "Based on the scenario, what shape will the front view of the tank show?",
    "scenario": "A cylindrical water storage tank with diameter 3 m and height 5 m is placed upright on a flat roof. A structural engineer needs to draw the orthographic projections of the tank for the building plan. The tank's axis is vertical (perpendicular to the ground/HP).",
    "correct_answer": "A",
    "explanation": "A cylinder with vertical axis (⊥ HP) has its front view as a rectangle. The width = diameter = 3 m and the height = tank height = 5 m. So the front view is a 3 m × 5 m rectangle.",
    "options": [
        opt("A", "A rectangle of 3 m width and 5 m height", True),
        opt("B", "A circle of 3 m diameter"),
        opt("C", "A triangle of 3 m base and 5 m height"),
        opt("D", "An ellipse"),
    ],
    "elimination_hints": [
        hint("B", "A circle is the top view of this cylinder, not the front view.", "Confusing top and front views"),
        hint("C", "A triangle is the front view of a cone, not a cylinder.", "Confusing cylinder with cone"),
        hint("D", "An ellipse would appear if the circular cross-section were inclined to the viewing plane, not for a vertical cylinder.", "Applying inclined-axis projection to vertical axis"),
    ]
})
questions.append(q37)

q38 = base("cuet-eg-solids-38", "scenario-based", "hard", "evaluate", "Monument Projection", ["real-world", "pyramid-projection"])
q38.update({
    "question_text": "Based on the scenario, what is the slant height of the pyramidal roof as seen in the front view?",
    "scenario": "An architect is designing a monument with a square pyramidal roof. The base of the pyramid is a square with 8 m side, and the vertical height of the pyramid is 6 m. The pyramid sits on a 4 m high rectangular pedestal. The axis of the pyramid is vertical. A side of the base is parallel to the VP.",
    "correct_answer": "B",
    "explanation": "When a side of the square base is parallel to VP, the front view shows a triangular outline. The slant height seen in the FV is the distance from the apex to the midpoint of the front base edge. This = sqrt(height² + (half-side)²) = sqrt(6² + 4²) = sqrt(36 + 16) = sqrt(52) = 7.21 m.",
    "options": [
        opt("A", "6 m"),
        opt("B", "7.21 m", True),
        opt("C", "10 m"),
        opt("D", "5.66 m"),
    ],
    "elimination_hints": [
        hint("A", "6 m is the vertical height of the pyramid, not the slant height seen in the FV.", "Using axis height as slant height"),
        hint("C", "10 m = sqrt(6² + 8²) uses the full side (8 m) instead of half-side (4 m). The slant height in the FV goes to the midpoint of the edge.", "Using full side instead of half-side"),
        hint("D", "5.66 m = 8/sqrt(2) = half-diagonal of the base. This is the distance to a corner, not to the edge midpoint.", "Using half-diagonal instead of half-side"),
    ]
})
questions.append(q38)

# ═══════════════════════════════════════════════════════════════════════════════
# LOGICAL-SEQUENCE (2): cuet-eg-solids-39 to 40
# ═══════════════════════════════════════════════════════════════════════════════

q39 = base("cuet-eg-solids-39", "logical-sequence", "medium", "understand", "Drawing Solid Projections", ["projection-steps", "drawing-order"])
q39.update({
    "question_text": "Arrange the steps for drawing the projections of a hexagonal pyramid resting on its base on HP with a side of the base parallel to VP:",
    "items": [
        {"id": "1", "text": "Draw the XY reference line"},
        {"id": "2", "text": "Draw the top view as a regular hexagon with one side parallel to XY"},
        {"id": "3", "text": "Mark the center of the hexagon as the apex projection (o)"},
        {"id": "4", "text": "Draw lines from each corner to the center (o) representing slant edges in TV"},
        {"id": "5", "text": "Project all points vertically to the front view region above XY"},
        {"id": "6", "text": "Mark the apex at the required height and join to base corners for the FV triangle"}
    ],
    "correct_order": ["1", "2", "3", "4", "5", "6"],
    "correct_answer": "D",
    "explanation": "Correct order: Draw XY → Draw hexagonal TV → Mark apex center → Draw slant edges in TV → Project to FV region → Complete FV with apex height.",
    "options": [
        opt("A", "1, 5, 2, 3, 4, 6"),
        opt("B", "1, 2, 5, 3, 4, 6"),
        opt("C", "2, 1, 3, 4, 5, 6"),
        opt("D", "1, 2, 3, 4, 5, 6", True),
    ],
    "elimination_hints": [
        hint("A", "Step 5 (projecting to FV) cannot come before Step 2 (drawing the TV). You need the TV points to project from.", "Projecting before having the source points"),
        hint("B", "Step 5 (projecting to FV) should come after completing the TV (steps 2-4), not between steps 2 and 3.", "Premature projection to FV"),
        hint("C", "Step 2 (hexagon) cannot be drawn before Step 1 (XY line), as XY provides the reference frame.", "Drawing without the reference line"),
    ]
})
questions.append(q39)

q40 = base("cuet-eg-solids-40", "logical-sequence", "hard", "analyze", "Two-Step Method for Inclined Axis", ["two-step-method", "construction-order"])
q40.update({
    "question_text": "Arrange the steps for drawing projections of a cone with axis inclined at 45° to HP and parallel to VP (two-step method):",
    "items": [
        {"id": "1", "text": "Draw the cone with axis perpendicular to HP (FV = triangle, TV = circle)"},
        {"id": "2", "text": "Divide the base circle in TV into 12 equal parts and label them"},
        {"id": "3", "text": "Project these 12 points to the front view and mark their heights"},
        {"id": "4", "text": "Redraw the FV triangle tilted at 45° to XY (keeping the base on XY or at required height)"},
        {"id": "5", "text": "From the tilted FV, project the 12 points vertically down to get the new TV"},
        {"id": "6", "text": "Transfer horizontal distances from Step 1 TV to get the new TV points and draw the foreshortened elliptical base"}
    ],
    "correct_order": ["1", "2", "3", "4", "5", "6"],
    "correct_answer": "C",
    "explanation": "Two-step method for cone: Draw upright cone → Divide base circle into 12 parts → Project to FV → Tilt FV to 45° → Project tilted points down → Use Step 1 horizontal distances for new TV to get elliptical base.",
    "options": [
        opt("A", "1, 4, 2, 3, 5, 6"),
        opt("B", "1, 2, 4, 3, 5, 6"),
        opt("C", "1, 2, 3, 4, 5, 6", True),
        opt("D", "4, 1, 2, 3, 5, 6"),
    ],
    "elimination_hints": [
        hint("A", "Step 4 (tilting FV) before Step 2 (dividing circle) means you lose the reference points. Division must happen in Step 1 position.", "Tilting before establishing reference points"),
        hint("B", "Step 4 (tilting) before Step 3 (projecting to FV) means the points aren't on the FV yet. You need FV points before tilting.", "Tilting before completing the initial FV"),
        hint("D", "Step 4 (tilting) cannot be the first step. The upright position (Step 1) must be drawn first to establish the true base shape.", "Tilting before drawing the initial position"),
    ]
})
questions.append(q40)

# ═══════════════════════════════════════════════════════════════════════════════
# WRITE & VALIDATE
# ═══════════════════════════════════════════════════════════════════════════════

with open(OUT, 'w') as f:
    json.dump(questions, f, indent=2, ensure_ascii=False)

print(f"Written {len(questions)} questions to {OUT}")

ids = [q["id"] for q in questions]
assert len(ids) == 40, f"Expected 40, got {len(ids)}"
assert len(set(ids)) == 40, "Duplicate IDs found!"

from collections import Counter
answers = Counter(q["correct_answer"] for q in questions)
print(f"Answer distribution: {dict(answers)}")
for letter, count in answers.items():
    assert count <= 12, f"Answer {letter} appears {count} times (max 12)"

types = Counter(q["question_type"] for q in questions)
print(f"Type distribution: {dict(types)}")

diffs = Counter(q["difficulty"] for q in questions)
print(f"Difficulty distribution: {dict(diffs)}")

print("All validations passed!")
